In [30]:
from sqlalchemy import create_engine as c_e

In [15]:
from sqlalchemy.dialects.mysql import VARCHAR, YEAR, TINYTEXT, LONGTEXT
from werkzeug.security import generate_password_hash

database = SQLAlchemy()
login_mng = LoginManager()

roles = {
    "admin":0,
    "editor":1,
    "user":2
}

class User(UserMixin, database.Model):
    __tablename__ = 'users'
    id = database.Column("id",
        database.Integer,
        primary_key=True,
        autoincrement=True)
    username = database.Column("username", TINYTEXT)
    role = database.Column("role", TINYTEXT)
    password = database.Column("password", TINYTEXT)
    email = database.Column("email", TINYTEXT)

    def __repr__(self):
        return f"{self.username}: {self.role}"

    def has_roles(self, role):
        cur = roles.get(self.role, 10)
        inp = roles.get(role, 0)
        return cur <= inp

    def roles_range(self, role_lower, role_upper):
        cur = roles.get(self.role, 10)
        low = roles.get(role_lower, 0)
        up = roles.get(role_upper, 0)
        return (low <= cur) and (cur <= up)

@event.listens_for(User.password, "set", retval=True)
def hash_user_password(target, value, oldvalue, initiator):
    if value != oldvalue:
        return generate_password_hash(value)
    return value

class FkColumn(database.Column):
    def __init__(self, colname:str, refers:str):
        super(FkColumn, self).__init__(colname,
            database.Integer,
            database.ForeignKey(refers))

def common_repr(self):
    return f"id {self.id}: {self.main}"

def rel_table_repr(self):
    return f"{self.id}: entry {self.main} maps to {self.refer}"

class Years(database.Model):
    __tablename__="years"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("year", YEAR(4))
    __repr__ = common_repr

class Keywords(database.Model):
    __tablename__="keywords"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("keyword", VARCHAR(45))
    __repr__ = common_repr

class Rayons(database.Model):
    __tablename__="rayons"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("ray", TINYTEXT)
    __repr__ = common_repr

class Files(database.Model):
    __tablename__ = "files"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("name", VARCHAR(80))
    __repr__ = common_repr

class VillsInf(database.Model):
    __tablename__ = "vills_inf"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("v_name", VARCHAR(25))
    ray = database.relationship("Rayons", secondary="vi2r")
    __repr__ = common_repr

class VillsTxt(database.Model):
    __tablename__ = "vills_txt"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("v_name", VARCHAR(25))
    ray = database.relationship("Rayons", secondary="vt2r")
    __repr__ = common_repr

class Informants(database.Model):
    __tablename__ = "informators"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("name", TINYTEXT)
    code = database.Column("code", VARCHAR(8))
    bio = database.Column("bio", database.Text)
    vill = database.relationship("VillsInf", secondary="i2vi")
    def __repr__(self):
        return f"{self.id}: {self.main} {self.code}"

class Collectors(database.Model):
    __tablename__ = "collectors"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = database.Column("name", TINYTEXT)
    code = database.Column("code", VARCHAR(8))
    __repr__ = common_repr

class Questions(database.Model):
    __tablename__ = "questions"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    q_list = database.Column("q_list", VARCHAR(6)) 
    q_num = database.Column("q_num", VARCHAR(5))
    q_let = database.Column("q_let", VARCHAR(3))
    q_txt = database.Column("q_txt", database.Text)
    q_theme = database.Column("q_theme", database.Text)
    def __repr__(self):
        return f"{self.id}: {self.q_txt}"

class Texts(database.Model):
    __tablename__ = "texts"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    text = database.Column("text", LONGTEXT)
    keyword = database.relationship("Keywords", secondary="t2k")
    year = database.relationship("Years", secondary="t2y")
    informator = database.relationship("Informants", secondary="t2i")
    collector = database.relationship("Collectors", secondary="t2s")
    file = database.relationship("Files", secondary="t2f")
    question = database.relationship("Questions", secondary="t2q")
    vill = database.relationship("VillsTxt", secondary="t2v")
    def __repr__(self):
        return f"{self.id} {self.text}"

class Text2vill(database.Model):
    __tablename__ = "t2v"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("v_id", "vills_txt.id")
    __repr__ = rel_table_repr

class Inf2vill(database.Model):
    __tablename__ = "i2vi"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("i_id", "informators.id")
    refer = FkColumn("v_id", "vills_inf.id")
    __repr__ = rel_table_repr    

class Vill2ray(database.Model):
    __tablename__ = "vt2r"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("v_id", "vills_txt.id")
    refer = FkColumn("r_id", "rayons.id")
    __repr__ = rel_table_repr    

class VI2ray(database.Model):
    __tablename__ = "vi2r"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("v_id", "vills_inf.id")
    refer = FkColumn("r_id", "rayons.id")
    __repr__ = rel_table_repr 

class Text2year(database.Model):
    __tablename__ = "t2y"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("y_id", "years.id")
    __repr__ = rel_table_repr

class Text2key(database.Model):
    __tablename__ = "t2k"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("k_id", "keywords.id")
    __repr__ = rel_table_repr    

class Text2quest(database.Model):
    __tablename__ = "t2q"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("q_id", "questions.id")
    __repr__ = rel_table_repr 

class Text2file(database.Model):
    __tablename__ = "t2f"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("f_id", "files.id")
    __repr__ = rel_table_repr 

class Text2sob(database.Model):
    __tablename__ = "t2s"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("s_id", "collectors.id")
    __repr__ = rel_table_repr 

class Text2inf(database.Model):
    __tablename__ = "t2i"
    id = database.Column("id", database.Integer, primary_key=True, autoincrement=True)
    main = FkColumn("t_id", "texts.id")
    refer = FkColumn("i_id", "informators.id")
    __repr__ = rel_table_repr 


In [22]:
db = database.create_engine("mysql+pymysql://root:qwerty@localhost:3306/f_test", {})

In [31]:
engine = c_e("mysql+pymysql://root:qwerty@localhost:3306/f_test")

In [33]:
with engine.connect() as connection:
    with connection.begin():
        res = connection.execute(User.select())
        print(res)

AttributeError: type object 'User' has no attribute 'select'

In [23]:
with db.connect() as connection:
    result = connection.execute("select * from texts limit 5")
    for row in result:
        print("text: ", row["text"])

text:  Молодых привезли ко мне в дом, нать знать их благословлять. Вот их хлебом и благословляли, отломили по кусочку. Такой просто коровай испецч+ём, бе́лое тесто. Такой круглой. Они [молодые] сами отломят.
text:  [На свадьбу] стряпня́ красивая вышла, там пироги, - знать хорошо будут жить [молодые]
text:  Как дождь во время свадьбы, наверно эти молодые будут хорошо жить.
text:  Если идешь в приёмыши [если жених будет жить в доме у невесты], надо поспать на бороне [жениху].
text:  [Было гадание, когда мусор выметали и в подол клали?] э́то кла́ли... кла́ли, наве́рно... я то́же слыха́ла: э́тот му́сор, когда́ сва́дьба. Вот когда́ сва́дьба, дак оне́ э́то схо́дят, му́сор опа́шут да и... в подо́л-от сперва́ складу́т, а пото́м э́тот му́сор в носовичц+ёк завя́жут э́тот му́сор [...] и по́йдут на сва́дьбу, и бро́сят в воду - там вода́ у них где́-ка есть, дак в во́ду. [В ведро?] Вот, в ведро́. Во, в ведро́, дак они́ ху́до жить бу́дут. [Молодые?] Молоды́ ху́до жить бу́дут. Ну, е́сли там-от мужи́к 

In [24]:
quest = Questions.query.all()

RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.

In [34]:
import numpy as np

In [35]:
matrix = np.array([[-4, 1, 0],[0, -4, 1],[0, 0, -4]])

In [42]:
matrix

array([[-4,  1,  0],
       [ 0, -4,  1],
       [ 0,  0, -4]])

In [41]:
np.matmul(matrix, matrix)

array([[16, -8,  1],
       [ 0, 16, -8],
       [ 0,  0, 16]])

In [38]:
np.matmul(matrix, (np.matmul(matrix, matrix)))

array([[-64,  48, -12],
       [  0, -64,  48],
       [  0,   0, -64]])

In [40]:
np.matmul(np.matmul(matrix, matrix), np.matmul(matrix, matrix))

array([[ 256, -256,   96],
       [   0,  256, -256],
       [   0,    0,  256]])

In [43]:
matrix_2 = np.array([[2, 1, 0, 0, 0],[0, 2, 0, 0, 0],[0, 0, -5, 1, 0],[0, 0, 0, -5, 1],[0, 0, 0, 0, -5]])

In [44]:
matrix_2

array([[ 2,  1,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0, -5,  1,  0],
       [ 0,  0,  0, -5,  1],
       [ 0,  0,  0,  0, -5]])

In [45]:
np.matmul(matrix_2, matrix_2)

array([[  4,   4,   0,   0,   0],
       [  0,   4,   0,   0,   0],
       [  0,   0,  25, -10,   1],
       [  0,   0,   0,  25, -10],
       [  0,   0,   0,   0,  25]])

In [46]:
np.matmul(matrix_2, np.matmul(matrix_2, matrix_2))

array([[   8,   12,    0,    0,    0],
       [   0,    8,    0,    0,    0],
       [   0,    0, -125,   75,  -15],
       [   0,    0,    0, -125,   75],
       [   0,    0,    0,    0, -125]])

In [47]:
np.matmul(np.matmul(matrix_2, matrix_2), np.matmul(matrix_2, matrix_2))

array([[  16,   32,    0,    0,    0],
       [   0,   16,    0,    0,    0],
       [   0,    0,  625, -500,  150],
       [   0,    0,    0,  625, -500],
       [   0,    0,    0,    0,  625]])

In [58]:
mm = np.array([[1, 5, 2, -2, 6], [1, -3, 0, 1, -2], [2, 1, -3, 2, -5], [4, 3, -1, 1, 1], [3, -2, -3, 3, 7]])

In [60]:
mm = np.array([[5, 2, -2, 6], [-3, 0, 1, -2], [1, -3, 2, -5], [3, -1, 1, 1]])

In [63]:
that = np.array([[0, 4, 2], [-3, 5, 0]])
this = np.array([[7, 3], [5, -2], [12, 0]])
print(np.matmul(that, this))

[[ 44  -8]
 [  4 -19]]


In [67]:
np.array(np.linalg.inv(np.array([[1, 0, -2, -6], [2, 3, 1, 2], [1, 2, 3, 4], [1, 1, 1, -1]])), dtype=int)

array([[ 16,  -5,  21, -25],
       [-12,   4, -16,  19],
       [  0,   0,   0,   1],
       [  2,   0,   3,  -4]])